
###
#
# {{ $dotenv _CLIENT_SECRET }}
#
@GATEWAY_URL = http://localhost:8088
@GOSPORTSAGENT_URL = {{GATEWAY_URL}}/api/gosportsagent
@ODDSTRACKER_URL = {{GATEWAY_URL}}/api/oddstracker
@ROTOREADER_URL = {{GATEWAY_URL}}/api/rotoreader
@PROMETHEUS_URL = http://localhost:30090
#
#
###
################################ Gateway ################################
# Gateway API Docs
GET {{GATEWAY_URL}}/api-docs
###
# Aggregate API Docs
GET {{GATEWAY_URL}}/swagger-ui.html
###
#
#
################################ HealthChecks ################################ 
# Health Check API - oddstracker
GET {{ODDSTRACKER_URL}}
###
# Health Check API - gosportsagent
GET {{GOSPORTSAGENT_URL}}/healthz
###
# Health Check API - rotoreader
GET {{ROTOREADER_URL}}
###
#
#
#
################################ Go SportsAgent ################################
#
# Get Declared tools
GET {{GOSPORTSAGENT_URL}}/tools
###
# Prometheus metrics
GET {{GOSPORTSAGENT_URL}}/metrics
###
#
#
################################ oddstracker ################################
#
#
#
POST {{ODDSTRACKER_URL}}/collect?provider_key=theoddsapi
#
###
GET {{ODDSTRACKER_URL}}/event
###
# Test Prometheus Endpoint
GET {{ODDSTRACKER_URL}}/metrics
###
# Get docs
GET {{ODDSTRACKER_URL}}/docs
###
# Get docs
GET {{ODDSTRACKER_URL}}/openapi.json
###
#
#
#
#
################################ rotoreader ################################ 
#
#
#
###
GET {{ROTOREADER_URL}}/feed?size=1
###
PUT {{ROTOREADER_URL}}/collect
###
#
# Prometheus
GET {{PROMETHEUS_URL}}/api/v1/query?query=up
###
# GET {{PROMETHEUS_URL}}/api/v1/query?query={namespace="sportsstack"}
GET {{PROMETHEUS_URL}}/api/v1/query?query=%7Bnamespace%3D%22sportsstack%22%7D

###
GET {{PROMETHEUS_URL}}/api/v1/query?query=http_requests_total
#
###
GET {{PROMETHEUS_URL}}/api/v1/query?query=go_goroutines
###