image:
  repository: maxo5499/sportsstack-rotoreader
  tag: latest

replicas: 2

env:
  logLevel: INFO
  rootDir: /app

hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75

cronjob:
  schedule: "0 * * * *"
