image:
  repository: maxo5499/sportsstack-rotoreader
  tag: latest

replicas: 1

env:
  logLevel: INFO
  rootDir: /app

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75

cronjob:
  schedule: "* */2 * * *"
