apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sportsstack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: maxo5499/sportsstack-api-gateway:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ODDSTRACKER_SERVICE_URL
              value: http://oddstracker:8080
            - name: ROTOREADER_SERVICE_URL
              value: http://rotoreader:8081
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS
              value: always
            - name: MANAGEMENT_HEALTH_CIRCUITBREAKERS_ENABLED
              value: "true"
          ports:
            - containerPort: 8088
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: sportsstack
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 8088
      targetPort: 8088
      name: http
