apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sportsstack
spec:
  replicas: {{ .Values.replicas }}
  strategy: 
    type: {{ .Values.strategy.type}}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: ODDSTRACKER_SERVICE_URL
              value: {{ .Values.env.oddstrackerServiceUrl | quote }}
            - name: ROTOREADER_SERVICE_URL
              value: {{ .Values.env.rotoreaderServiceUrl | quote }}
            - name: GOSPORTSAGENT_SERVICE_URL
              value: {{ .Values.env.gosportsagentServiceUrl | quote }}
          ports:
            - containerPort: 8088
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
