apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceNames.configMap }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_HOST: {{ ternary .Values.serviceNames.postgres .Values.postgres.host (eq .Values.mode "incluster") | quote }}
  POSTGRES_PORT: {{ printf "%d" .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
