apiVersion: v2
name: observability
version: 0.1.0
description: Helm umbrella chart for local observability stack
kubeVersion: ">=1.23.0"
type: application

dependencies:
- name: prometheus
  version: 25.8.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
- name: grafana
  version: 8.3.5
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
- name: loki-stack
  version: 2.10.2
  repository: https://grafana.github.io/helm-charts
  condition: loki-stack.enabled
- name: tempo
  version: 1.10.0
  repository: https://grafana.github.io/helm-charts
  condition: tempo.enabled