prometheus:
  enabled: true
  alertmanager:
    enabled: false
  kubeStateMetrics:
    enabled: false
  pushgateway:
    enabled: false
  server:
    service:
      type: NodePort
      nodePort: 30090
    persistentVolume:
      enabled: false

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30300
  persistence:
    enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://observability-prometheus-server
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://observability-loki:3100
        isDefault: false

loki-stack:
  enabled: true
  loki:
    enabled: true
    persistence:
      enabled: false
    config:
      auth_enabled: false
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
        chunk_idle_period: 3m
        chunk_block_size: 262144
        chunk_retain_period: 1m
        max_transfer_retries: 0
      schema_config:
        configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/boltdb-shipper-active
          cache_location: /data/loki/boltdb-shipper-cache
          cache_ttl: 24h
          shared_store: filesystem
        filesystem:
          directory: /data/loki/chunks
      compactor:
        working_directory: /data/loki/boltdb-shipper-compactor
        shared_store: filesystem
      limits_config:
        reject_old_samples: true
        reject_old_samples_max_age: 168h
  promtail:
    enabled: true
    config:
      clients:
      - url: http://observability-loki:3100/loki/api/v1/push
  grafana:
    enabled: false
  prometheus:
    enabled: false
