apiVersion: v1
kind: Service
metadata:
  name: rotoreader
  namespace: sportsstack
spec:
  type: ClusterIP
  selector:
    app: rotoreader
  ports:
    - port: 8081
      targetPort: 8081
      name: http
