image:
  repository: maxo5499/sportsstack-go-sportsagent
  tag: latest

replicas: 1

env:
  apiGatewayServiceUrl: http://api-gateway:8088
  oddstrackerServiceUrl: http://api-gateway:8088/api/oddstracker
  rotoreaderServiceUrl: http://api-gateway:8088/api/rotoreader

otel:
  enabled: true
  serviceName: go-sportsagent
  exporterEndpoint: http://observability-tempo:4317
  exporterProtocol: grpc
  exporterInsecure: true
  tracesEndpoint: http://observability-tempo:4317
  tracesProtocol: grpc
  resourceAttributes: service.namespace=sportsstack
  tracesExporter: otlp
  metricsExporter: none
  logsExporter: none
  propagators: tracecontext,baggage
  tracesSampler: parentbased_always_on
  logLevel: info

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
